### ISSUE TITLE
请问一下还是没有找到

### ISSUE THREAD

**Issue by sonwa** [rpcxio/protoc-gen-rpcx#1]
请问一下还是没有找到rpcx插件是什么原因？按你的指令已经是正常安装，文件复到了protoc-gen-go。安装时没出错的

![image](https://user-images.githubusercontent.com/1425134/84649778-b30a1300-af39-11ea-8c02-f7fc29f2b8c3.png)

**Comment by smallnest** [comment]
保证你编译的`protoc-gen-go`在`PATH`中，并且PATH中没有原来的`protoc-gen-go`.

看你的日志貌似编译时找的是PATH路径里老的`protoc-gen-go`

**Comment by sonwa** [comment]
的确是旧的影响了，删了旧的重新用git下一次就可以了
