### ISSUE TITLE
安装插件的时候报错

### ISSUE THREAD

**Issue by iaimstar** [rpcxio/protoc-gen-rpcx#5]
go install github.com/rpcxio/protoc-gen-rpcx@latest

go: finding module for package github.com/golang/protobuf/protoc-gen-go/rpcx
go\pkg\mod\github.com\rpcxio\protoc-gen-rpcx@v0.2.2\link_rpcx.go:3:8: module github.com/golang/protobuf@latest found (v1.5.2), but does not contain package github.com/golang/protobuf/protoc-gen-go/rpcx

**Comment by iaimstar** [comment]
环境是win10，go 1.18
我机器上预先安装有google官方的protobuf 的protoc和gen

**Comment by smallnest** [comment]
这两个安装一下：

```sh
go install github.com/golang/protobuf/protoc-gen-go@latest
go install github.com/gogo/protobuf/protoc-gen-gofast@latest
```

**Comment by smallnest** [comment]
@iaimstar
