### ISSUE TITLE
go install github.com/rpcxio/protoc-gen-go@latest 报错

### ISSUE THREAD

**Issue by joveth1** [rpcxio/protoc-gen-rpcx#8]
go install github.com/rpcxio/protoc-gen-go@latest
go: github.com/rpcxio/protoc-gen-go@latest: module github.com/rpcxio/protoc-gen-go: git ls-remote -q origin in C:\Users\test2\go\pkg\mod\cache\vcs\5d3137341ca25158baa619806a7c8a92905759d27e2ddc7a1cc99ce77fe7e089: exit status 128:
        ERROR: Repository not found.
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.

另外，这个插件跟 protoc-gen-gogorpcx 有什么区别呢？ 我用 protoc-gen-gogorpcx 生成的 go文件中 里面的 内容

proto "github.com/golang/protobuf/proto"  提示 deprecated

**Comment by smallnest** [comment]
see the readme:
<img width="881" alt="image" src="https://github.com/rpcxio/protoc-gen-rpcx/assets/865763/aa53235f-7210-44b8-b5ed-2b76044a4679">

**Comment by smallnest** [comment]
protoc-gen-gogorpcx  uses gogo lib
